// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wAM3-qxnfTO7TczbLnX3DwJof3wbfRM',
    appId: '1:619604146805:web:dc6b9e128eacb552c4163c',
    messagingSenderId: '619604146805',
    projectId: 'psikitechdiagnos-80803',
    authDomain: 'psikitechdiagnos-80803.firebaseapp.com',
    storageBucket: 'psikitechdiagnos-80803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXenZhErtRmiHXSeKDYzMjIoFTWRxZ4I',
    appId: '1:619604146805:android:9c05aa65de5f1fe2c4163c',
    messagingSenderId: '619604146805',
    projectId: 'psikitechdiagnos-80803',
    storageBucket: 'psikitechdiagnos-80803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkb4gbiigAsW2Arzs1a6i9L34uvLlGCsk',
    appId: '1:619604146805:ios:57bdf20ad7d8c163c4163c',
    messagingSenderId: '619604146805',
    projectId: 'psikitechdiagnos-80803',
    storageBucket: 'psikitechdiagnos-80803.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkb4gbiigAsW2Arzs1a6i9L34uvLlGCsk',
    appId: '1:619604146805:ios:57bdf20ad7d8c163c4163c',
    messagingSenderId: '619604146805',
    projectId: 'psikitechdiagnos-80803',
    storageBucket: 'psikitechdiagnos-80803.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-wAM3-qxnfTO7TczbLnX3DwJof3wbfRM',
    appId: '1:619604146805:web:b9620ae8bd11d9f3c4163c',
    messagingSenderId: '619604146805',
    projectId: 'psikitechdiagnos-80803',
    authDomain: 'psikitechdiagnos-80803.firebaseapp.com',
    storageBucket: 'psikitechdiagnos-80803.firebasestorage.app',
  );
}
